name: grass79_conda
channels:
  - conda-forge
dependencies:
  - clang_osx-64
  - clangxx_osx-64
  - setuptools
  - python <3.7.0
  - numpy
  - gdal >2
  - freetype
  - cairo
  - matplotlib
  - pandoc
  - pillow
  - wxpython
  - sqlite
  - jpeg
  - libpng
  - libtiff
  - pkg-config
  - libiconv
  - fftw
  - blas
  - giflib
  - proj
  - geos
  - krb5
  - gettext
  - lastools
  - ghostscript
  - zstd
  - pdal
