name: CI

on: [push]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - name: brew install
      run: |
        brew tap osgeo/osgeo4mac
        brew install osgeo-grass
    - name: brew test
      run: |
        brew test -v osgeo-grass
    - name: Basic test of GRASS GIS
      run: ./test_simple.sh
    - name: Thorough test of GRASS GIS
      run: ./test_thorough.sh
