name: CI

on: [push]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - name: Prepare conda environment
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: 3.6.10
        activate-environment: grass79_conda
        environment-file: environment.yml
    - name: Get and build GRASS GIS
      shell: bash -l {0}
      run: ./build.sh
    - name: Basic test of GRASS GIS
      shell: bash -l {0}
      run: ./test_simple.sh
    - name: Thorough test of GRASS GIS
      shell: bash -l {0}
      run: ./test_thorough.sh
