name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget git gawk findutils
        xargs -a <(awk '! /^ *(#|$)/' "apt.txt") -r -- \
            sudo apt-get install -y --no-install-recommends --no-install-suggests
    - name: Create installation directory
      run: |
        mkdir $HOME/install
    - name: Set number of cores for compilation
      run: |
        echo "::set-env name=MAKEFLAGS::-j$(nproc)"
    - name: Set LD_LIBRARY_PATH for GRASS GIS compilation
      run: |
        echo "::set-env name=LD_LIBRARY_PATH::$HOME/install/lib"
    - name: Get and compile GRASS GIS
      run: ./compile.sh $HOME/install
    - name: Add the bin directory to PATH
      run: |
        echo "::add-path::$HOME/install/bin"
    - name: Basic test of GRASS GIS
      run: ./test_simple.sh
    - name: Thorough test of GRASS GIS
      run: ./test_thorough.sh
