name: Code quality check

on: [push]

jobs:
  flake8:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Download GRASS GIS
      run: |
        git clone https://github.com/OSGeo/grass.git --branch master --depth=1
    - name: Put configuration file in place
      run: |
        cp .flake8 grass/lib/python
    - name: Run Flake8
      run: |
        cd grass/lib/python
        flake8 --count --statistics --show-source .
